// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ui

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const GUIDiUserConsentVerifierStatics string = "af4f3f91-564c-4ddc-b8b5-973447627c65"
const SignatureiUserConsentVerifierStatics string = "{af4f3f91-564c-4ddc-b8b5-973447627c65}"

type iUserConsentVerifierStatics struct {
	ole.IInspectable
}

type iUserConsentVerifierStaticsVtbl struct {
	ole.IInspectableVtbl

	UserConsentVerifierCheckAvailabilityAsync   uintptr
	UserConsentVerifierRequestVerificationAsync uintptr
}

func (v *iUserConsentVerifierStatics) VTable() *iUserConsentVerifierStaticsVtbl {
	return (*iUserConsentVerifierStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func UserConsentVerifierCheckAvailabilityAsync() (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Credentials.UI.UserConsentVerifier", ole.NewGUID(GUIDiUserConsentVerifierStatics))
	if err != nil {
		return nil, err
	}
	v := (*iUserConsentVerifierStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().UserConsentVerifierCheckAvailabilityAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func UserConsentVerifierRequestVerificationAsync(message string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Credentials.UI.UserConsentVerifier", ole.NewGUID(GUIDiUserConsentVerifierStatics))
	if err != nil {
		return nil, err
	}
	v := (*iUserConsentVerifierStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	messageHStr, err := ole.NewHString(message)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().UserConsentVerifierRequestVerificationAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(messageHStr),          // in string
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
